[settings]
sound_file = "/System/Library/Sounds/Ping.aiff"
alarm_interval = 5  # seconds between alarm repeats
max_alarm_duration = 300  # maximum alarm duration in seconds (5 minutes)
skip_days = ["sunday"]

[time_blocks]
# time in minutes
pomodoro = 25
long_break = 40
meeting = 50
exercise = 30
lunch = 60
napping = 30

[time_points]
go_to_bed = "ä¸ŠåºŠç¡è§‰ ğŸ˜´ è¯¥ä¼‘æ¯äº†ï¼"
summary_time = "ä»Šå¤©çš„å·¥ä½œç»“æŸ ğŸ‰, æ€»ç»“ä¸€ä¸‹"