[settings]
sound_file = "/System/Library/Sounds/Ping.aiff"
alarm_interval = 5  # seconds between alarm repeats
max_alarm_duration = 300  # maximum alarm duration in seconds (5 minutes)
skip_days = ["sunday"]

[time_blocks]
# time in minutes
pomodoro = 25
potato = 50
long_break = 40
meeting = 50

[time_points]
go_to_bed = "ä¸ŠåºŠç¡è§‰ ğŸ˜´ è¯¥ä¼‘æ¯äº†ï¼"
summary_time = "ä»Šå¤©çš„å·¥ä½œç»“æŸ ğŸ‰, æ€»ç»“ä¸€ä¸‹"
napping = "å°æ†©æ—¶é—´åˆ° ğŸ˜´, ä¼‘æ¯ä¸€ä¸‹å§ï¼"
lunch_time = "åˆé¤æ—¶é—´åˆ° ğŸ±ï¼"
exercise = "è¿åŠ¨æ—¶é—´åˆ° ğŸƒâ€â™‚ï¸ï¼æ´»åŠ¨æ´»åŠ¨èº«ä½“å§ï¼"

[tasks]
daily_urgent = ["08:31", "14:01", "17:31", "21:31"]
daily_summary = "23:35"
weekly_review = "sunday 20:00"
monthly_review = "1 20:00"

[paths]
# Directory containing configuration files
config_dir = "config"

reports_path = "~/Desktop/reports"
