# Schedule Configuration
# Time format: "HH:MM" (24-hour format)
# Message: The reminder text to display

[monday]
"08:30" = "potato"
"09:30" = "potato"
"10:30" = "potato"
"11:30" = "potato"
"13:20" = "napping"



[tuesday]
"08:30" = "potato"
"09:30" = "potato"
"10:30" = "potato"
"11:30" = "potato"
"13:20" = "napping"
"14:00" = "potato"
"15:00" = "potato"
"16:00" = "potato"
"17:00" = "potato"


[wednesday]
"08:30" = "potato"
"09:30" = "pomodoro"

"13:20" = "napping"
"14:00" = "potato"
"15:00" = "potato"


[thursday]

"13:20" = "napping"
"14:00" = "potato"
"15:00" = "potato"
"16:00" = "potato"
"17:00" = "potato"

[friday]
"08:30" = "potato"
"09:30" = "pomodoro"

"13:20" = "napping"


[saturday]
"08:30" = "potato"
"09:30" = "potato"
"10:30" = "potato"
"11:30" = "potato"
"13:20" = "napping"
"14:00" = "potato"
"15:00" = "potato"
"16:00" = "potato"
"17:00" = "potato"

[sunday]
"08:30" = "potato"
"09:30" = "potato"
"10:30" = "potato"
"11:30" = "potato"
"13:20" = "napping"
"14:00" = "potato"
"15:00" = "potato"
"16:00" = "potato"
"17:00" = "potato"


[common]
"19:30" = "potato"
"20:30" = "pomodoro"
"21:30" = "pomodoro"
"22:30" = "go_to_bed"
"23:45" = "summary_time"
"23:55" = "go_to_bed"